release:

before:
  hooks:
    - go mod tidy
    - make test

builds:
- id: kubectl-skew
  main: ./cmd/kubectl-skew/main.go
  binary: kubectl-skew
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - amd64

archives:
- builds:
  - kubectl-skew
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
